services:
  - type: web
    name: medical-symptoms-agent
    env: python
    buildCommand: pip install --no-cache-dir -r requirements-render.txt
    startCommand: python run.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
